repos:
  - repo: local
    hooks:
      - id: add-signature
        name: Add signature to Python files
        entry: "C:/Users/Ibrahim/AppData/Local/Programs/Python/Python312/python.exe .pre-commit/add-signature.py"
        language: script
        files: \.py$